[versions]
jei = "19.21.0.247"
emi = "1.1.22+1.21.1"
crt = "21.0.35"
mekanism = "1.21.1-10.7.17.83"
shimmer = "1.20.1-0.2.4"
ccTweaked = "1.113.1"
cucumber = "1.21.1-8.0.9"
mysticalagriculture = "1.21.1-8.0.9"

## modrinth maven ##
sodium = "mc1.21.1-0.6.13-neoforge"
iris = "1.8.8+1.21.1-neoforge"
modernui = "RM220vWV" #3.12.0.2
jade = "15.10.3+neoforge"
jer = "1.6.0.17"
ferritecore = "7.0.2-neoforge"
modernfix = "4SPHwiDB" # 5.24.3+mc1.21.1

## curseforge maven ##
mekanismcovers = "6071684"
igleelibrary = "7000755"
evolvedmekanism = "7161187"
immersiveengineering = "6733669"

## libs ##
jech = "4.5.22"


[libraries]
jei-common-api      = { module = "mezz.jei:jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api       = { module = "mezz.jei:jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge-impl      = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
emi                 = { module = "dev.emi:emi-neoforge", version.ref = "emi" }
jer                 = { module = "maven.modrinth:just-enough-resources-jer", version.ref = "jer" }

cc-tweaked-core-api   = { module = "cc.tweaked:cc-tweaked-1.21.1-core-api", version.ref = "ccTweaked" }
cc-tweaked-forge-api  = { module = "cc.tweaked:cc-tweaked-1.21.1-forge-api", version.ref = "ccTweaked" }
cc-tweaked-forge-impl = { module = "cc.tweaked:cc-tweaked-1.21.1-forge", version.ref = "ccTweaked" }

mekanism            = { module = "mekanism:Mekanism", version.ref = "mekanism" }
shimmer             = { module = "com.lowdragmc.shimmer:Shimmer-forge", version.ref = "shimmer" }
crt                 = { module = "com.blamejared.crafttweaker:CraftTweaker-neoforge-1.21.1", version.ref = "crt" }
cucumber            = { module = "com.blakebr0.cucumber:Cucumber", version.ref = "cucumber" }
mysticalagriculture = { module = "com.blakebr0.mysticalagriculture:MysticalAgriculture", version.ref = "mysticalagriculture" }

jade                = { module = "maven.modrinth:jade", version.ref = "jade" }
sodium              = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris                = { module = "maven.modrinth:iris", version.ref = "iris" }
ferritecore         = { module = "maven.modrinth:uXXizFIs", version.ref = "ferritecore" }
modernfix           = { module = "maven.modrinth:modernfix", version.ref = "modernfix" }
modernui            = { module = "maven.modrinth:modern-ui", version.ref = "modernui" }

mekanismcovers      = { module = "curse.maven:mekanism-covers-1119874", version.ref = "mekanismcovers" }
igleelibrary        = { module = "curse.maven:iglee-library-541199", version.ref = "igleelibrary" }
evolvedmekanism     = { module = "curse.maven:evolved-mekanism-1230085", version.ref = "evolvedmekanism" }
immersiveengineering= { module = "curse.maven:immersive-engineering-231951", version.ref = "immersiveengineering" }

jecharacters        = { module = "dev:jecharacters-1.21-neoforge", version.ref = "jech" }
[bundles]
jei = ["jei-common-api", "jei-neoforge-api", "jei-neoforge-impl"]